on:
  push:
    branches:
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: calcit-lang/setup-cr@0.0.8

      - name: "prepare modules"
        run: >
          mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/
          && git clone https://github.com/calcit-lang/calcit-http.git
          && git clone https://github.com/calcit-lang/calcit-json.git
          && git clone https://github.com/calcit-lang/lilac.git
          && git clone https://github.com/calcit-lang/stir-template.git --branch 0.0.8

      - run: cr compact.cirru ir
