on:
  push:
    branches:
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/calcit-lang/calcit/releases/download/0.6.21/cr'
          name: 'cr'
          version: '0.6.21'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: "prepare modules"
        run: >
          mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/
          && git clone https://github.com/calcit-lang/calcit-http.git
          && git clone https://github.com/calcit-lang/calcit-json.git
          && git clone https://github.com/calcit-lang/lilac.git
          && git clone https://github.com/calcit-lang/stir-template.git --branch 0.0.7

      - run: cr -1 --emit-ir
